In [ ]:
import numpy as np

# Define input image
image = np.array([[1, 0, 2, 3],
                  [3, 1, 0, 1],
                  [2, 2, 0, 2],
                  [2, 0, 0, 1]])

# Define convolution kernel
kernel = np.array([[1, 0],
                   [0, 1]])

# Define max pooling parameters
pool_size = 2
stride = 2

# Perform convolution
def convolution(image, kernel):
    image_height, image_width = image.shape
    kernel_height, kernel_width = kernel.shape
    output_height = image_height - kernel_height + 1
    output_width = image_width - kernel_width + 1
    conv_output = np.zeros((output_height, output_width))

    for i in range(output_height):
        for j in range(output_width):
            conv_output[i, j] = np.sum(image[i:i+kernel_height, j:j+kernel_width] * kernel)

    return conv_output

conv_output = convolution(image, kernel)
print("Convolution Output:")
print(conv_output)

# Perform max pooling
def max_pooling(image, pool_size, stride):
    image_height, image_width = image.shape
    output_height = (image_height - pool_size) // stride + 1
    output_width = (image_width - pool_size) // stride + 1
    pooled_output = np.zeros((output_height, output_width))

    for i in range(0, image_height - pool_size + 1, stride):
        for j in range(0, image_width - pool_size + 1, stride):
            pooled_output[i//stride, j//stride] = np.max(image[i:i+pool_size, j:j+pool_size])

    return pooled_output

pooled_output = max_pooling(conv_output, pool_size, stride)
print("\nMax Pooling Output:")
print(pooled_output)


Convolution Output:
[[2. 0. 3.]
 [5. 1. 2.]
 [2. 2. 1.]]

Max Pooling Output:
[[5.]]
